	### 1️⃣ Get all todos
	GET http://localhost:5000/todos
	Content-Type: application/json

	###

	### 2️⃣ Add a new todo
	POST http://localhost:5000/todos
	Content-Type: application/json

	{
	"title": "Pray and read the Bible"
	}

	###

	### 3️⃣ Update a todo (replace :id with your real ID)
	PUT http://localhost:5000/todos/:id
	Content-Type: application/json

	{
	"completed": true
	}

	###

	### 4️⃣ Delete a todo (replace :id with your real ID)
	DELETE http://localhost:5000/todos/:id


	###

	### 4️⃣ Delete a todo (replace :id with your real ID)
	DELETE http://localhost:5000/todos/1761372800872
